// examples/taro/src/pages/index/index.tsx
import { Text, View } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import { useState } from 'react'

import { menuList } from './data'
import './index.css'

export default function Index() {
  const [bool, setBool] = useState<boolean>()

  useLoad(() => {
    console.log('Page loaded.')
  })

  return (
    <View className="aaa u-text-color text-center" p="4">
      <View className="flex justify-center space-x-2">
        <View className="i-tabler-carrot rotate-180 text-4xl" />
        <View className="h-10 w-10 bg-[hsl(2.7,81.9%,69.6%)]" />
      </View>
      <View
        className="border bg-blue-200 font-light font-mono"
        onClick={() => setBool(!bool)}
      >
        <View className="hover:text-red hover:font-bold !hover:bg-gray-600" text="#fff">
          hover bg-gray-600 text-red font-bold
        </View>
      </View>
      <View className={`m-2 p-2.5 ${bool ? 'p-0.5' : 'text-amber'}`}>
        {bool ? 'true' : 'false'}
      </View>
      <View flex="~ col gap-1" className="p-1" items-center>
        <View className="i-tabler:home inline-block text-xl text-blue" color="blue" />
        <View bg="green-(!200 800)">
          index
        </View>
      </View>
      <View flex="~ col" b="~ solid green dark:(red 2)">
        <View text-right h-10 flex="1" text="red">
          0123456789
        </View>
      </View>
      <View className="m-2 p-1 text-2xl">
        abckefghijklmnopqrstuvwxyz
      </View>
      <View flex="~" gap-2>
        {menuList.map((menu, idx) => (
          <View key={idx} className="[&>view]:first:text-green [&>view]:last:text-red">
            <View>{menu.name}</View>
            <View className={menu.icon} />
          </View>
        ))}
      </View>
      <View className="flex gap-2">
        <View className="flex-1 border-red border-solid divide-y-1 divide-red divide-dashed">
          <View className="custom-div">1</View>
          <View>2</View>
        </View>
        <View className="flex flex-1 space-x-1">
          <View className="custom-div w-20 border-1 border-blue border-solid">1</View>
          <View border-blue border-solid border-1 w-20>
            <Text>2</Text>
          </View>
        </View>
      </View>
    </View>
  )
}

// playgrounds/uni-app/src/pages/index/index.vue
<!-- eslint-disable @typescript-eslint/quotes -->
<script setup lang="ts">
import { ref } from 'vue'
import { menuList } from './data'
const bg = 'bg-[hsl(2.7,81.9%,69.6%)]'
const icon = "i-carbon:campsite"
const bgIgnore = 'applet-ignore bg-[hsl(2.7,81.9%,69.6%)]'
const index = 1
const bool = ref<boolean>()
const border = ref(true)
const fixed = ref(true)
</script>

<template>
  <div class="text-center aaa" p="4">
    <div text="4xl" class="rotate-180 i-carbon-campsite" :class="bg" />
    <div :class="[border && 'u-border-top', fixed && 'u-tabbar--fixed']" />
    <div class="border bg-blue-200 font-(light mono) ">
      <div class="hover:(!bg-gray-600 text-red font-bold)" text="#fff">
        {{ 'applet-ignore hover:(!bg-gray-600 text-red font-bold)' }}
      </div>
    </div>
    <div :class="`p-2.5 ${bool ? 'p-0.5' : 'text-amber'}`" m-2 :hover-class="['!bg-green']">
      class="applet-ignore hover:bg-green"
    </div>
    <div flex="~ col gap-1" class="p-1" items-center :class="bool ? 'text-yellow-500 px-2.5' : ''">
      <div :class="icon" inline-block color="blue" text="xl !red" />
      <div bg="green-(!200 800)">
        {{ `index${index + 1}` }}{{ `index` }}
      </div>
    </div>
    <div flex="~ col" b="~ solid green dark:(red 2)">
      <div text-right h-10 flex="1" text="red" :class="{ 'text-sm': index > 0 }">
        0123456789
      </div>
      <div
        h-10 flex="1" :class="[index > 1 ? '' : '']" text="blue dark:(red !bold)" :style="[index > 1 ? '' : '']"
        :type="index > 1"
      >
        {{ bgIgnore }}
      </div>
    </div>
    <div class="bg-[url(https://static.runoob.com/images/demo/demo2.jpg)]" w-40 h-20 ma un-color="red" bg="center cover">
      {{ 'applet-ignore bg-[url(https://static.runoob.com/images/demo/demo2.jpg)]' }}
    </div>
    <div class="p-1 text-2xl" m-2 :class="bool ? '' : 'text-yellow-500 p-2.5'">
      abckefghijklmnopqrstuvwxyz
    </div>
    <div i-carbon:logo-twitter dark:i-carbon:logo-github />
    <div i-carbon-logo-twitter dark:i-carbon-logo-github />
    <div flex="~" gap-2>
      <template v-for="menu, _idx of menuList" :key="_idx">
        <div class="[&>view]:last:text-red [&>view]:first:text-green [&+view]:text-2xl">
          <div>{{ menu.name }}</div>
          <div :class="menu.icon" />
        </div>
      </template>
      <div size="100" size-20 block bg-blue />
    </div>
  </div>
</template>

<style scoped></style>
